backend:
  name: github
  repo: Jackssgltd/selfstore-website
  branch: main

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/home.json"
        label: "Home"
        name: "home"
        fields:
          - { label: "Hero Title", name: "heroTitle", widget: "string" }
          - { label: "Hero Description", name: "heroDesc", widget: "text" }
          - { label: "Phone", name: "phone", widget: "string" }
          - { label: "Email", name: "email", widget: "string" }